### PR TITLE
Handle new TLC messages correctly

### PR DESCRIPTION
**Pull request by alygin**

### CODE REVIEW

**Comment by lemmy** [comment]
Does the vsix contain the latest TLC build?  Without it, TLC won't show the message.

**Comment by alygin** [comment]
This one does:  [vscode-tlaplus-1.4.0.vsix.zip](https://github.com/alygin/vscode-tlaplus/files/4073029/vscode-tlaplus-1.4.0.vsix.zip)

**Comment by quaeler** [comment]
I noticed that a message of type 1000 (`EC.GENERAL`) is treated as an error message - so the message
```
@!@!@STARTMSG 1000:0 @!@!@
Will generate a SpecTE file pair if error states are encountered.
@!@!@ENDMSG 1000 @!@!@
```
which will still appear in build 321 will still get listed as an Error in the VS Code display. 

(They will also appears for things like: 
```
@!@!@STARTMSG 1000:0 @!@!@
The model check run produced error-states - we will generate the SpecTE files now.
@!@!@ENDMSG 1000 @!@!@
@!@!@STARTMSG 1000:0 @!@!@
The file /Users/loki/arbeit/microsoft/specs/BlockingQueue-master/SpecTE.tla has been created.
@!@!@ENDMSG 1000 @!@!@
@!@!@STARTMSG 1000:0 @!@!@
The file /Users/loki/arbeit/microsoft/specs/BlockingQueue-master/SpecTE.cfg has been created.
@!@!@ENDMSG 1000 @!@!@
```
so perhaps 1000's should not be treated as error messages in the VS Code extension?)

**Comment by alygin** [comment]
@quaeler, thanks for noticing that!
Though, at the same time, there're lots of such places in the TLC code: https://github.com/tlaplus/tlaplus/blob/2f229f1d3e5ed1e2eadeff3bcd877b416e45d477/tlatools/src/tlc2/tool/distributed/fp/NonDistributedFPSetManager.java#L64

I guess you're right that treating them as simple info-messages would be more appropriate, but TLC code probably also needs refactoring to get rid of using 1000s for reporting errors.

**Comment by quaeler** [comment]
Yes, the messaging system is not the best thing.
For this case though, since there is the messaging "class" in addition to "code" which is captured in the `STARTMSG` lines, we can still segregate:
When `MP.printError(...` is used with `EC.GENERAL`, you will see `1000:1` whereas an `MP.printMessage(...` with `EC.GENERAL` will be `1000:0`.

So maybe, more correctly, treat `1000:0` not as error messages in the extension?

**Comment by alygin** [comment]
Oh, perfect, I'll use class to separate them. Thanks!

**Comment by alygin** [comment]
@quaeler, @lemmy, is it safe to always rely on the message class (severity level) when it's provided (0 - info, 1 and 2 - errors, 3 - warning, 4 - state)?

**Comment by lemmy** [comment]
I wouldn't put money on it.

**Comment by quaeler** [comment]
I'm slightly more optimistic than that - the only places in the tlatools code where those `MP` message class constants are being used for output are in the `MP.printMessage`, `printError`, `printTLCBug`, `printWarning`, and `printState`.
... so, unless consumer tlatools code is calling the logging method it really doesn't want to call (e.g in response to an exception catch, it is calling `printState` for some reason,) you should be able to rely on the classes.

**Comment by alygin** [comment]
@lemmy, with this fix, there must be no error messages in your scenario. It's now available in a pre-release version.

**Pull request merged**
